### PR TITLE
Cleanup motor information

### PR DESCRIPTION
**Pull request by helje5**
Also, make it a markdown.

### CODE REVIEW

**Comment by JorgePe** [comment]
I have no experience with github aand teams. There was a conflict with file, had to resolve manually, not sure if the final result is what you want, feel free to edit now.
Also changed to a markdown file.

**Comment by helje5** [comment]
Well, no, you dropped all my content ;-) Looks like only the rename made it through ;-)

**Comment by JorgePe** [comment]
Shouldn't renamed it mysef :( duh!

**Comment by helje5** [comment]
Maybe just try another merge.

**Pull request merged**
